name: Deploy Portfolio to AWS EC2 using SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/jabir-portfolio:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/jabir-portfolio:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to EC2 using AWS SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=i-00f47dfac4fb70d6a" \
            --comment "Deploy latest Docker image" \
            --parameters commands='[
              "docker pull '"${{ secrets.DOCKER_USERNAME }}"'/jabir-portfolio:latest",
              "docker stop portfolio || true",
              "docker rm portfolio || true",
              "docker run -d --name portfolio --restart unless-stopped -p 80:80 '"${{ secrets.DOCKER_USERNAME }}"'/jabir-portfolio:latest"
            ]' \
            --region us-east-1
